### ISSUE TITLE
Recommended approach

### ISSUE THREAD

**Issue by xfq** [w3c/localizable-manifests#5]
Several common approaches are currently listed in the document. Should we recommend one of them? Or is this document intended to be a comparison of the approaches and let the spec developers decide which one to use?

**Comment by aphillips** [comment]
It's the latter: each of these have their place (the list is not exhaustive, but merely shows what some common approaches are). We give advantages and disadvantages to help spec developers choose. We might call this out more explicitly, I guess?

**Comment by xfq** [comment]
I just read the document again and I think it is clearer now.

I filed this issue because I was asked which method should be used when designing a manifest format.

**Comment by aphillips** [comment]
Should I close this then?

**Comment by xfq** [comment]
Yes. Closing.
